name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Keystore and Generate Properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        run: |
          # 1. 解码并保存 Keystore 文件
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

          # 2. 动态生成 keystore.properties 文件
          cat <<EOF > keystore.properties
          storeFile=../keystore.jks
          storePassword=${{ secrets.STOREPASSWORD }}
          keyAlias=${{ secrets.KEYALIAS }}
          keyPassword=${{ secrets.KEYPASSWORD }}
          unprivKeyAlias=${{ secrets.UNPRIVKEYALIAS }}
          unprivKeyPassword=${{ secrets.UNPRIVKEYPASSWORD }}
          EOF

      - name: Build Release APK
        run: ./gradlew --no-daemon :app-unpriv:assembleRelease

      - name: Copy Debug Symbols to Release Path
        run: |
          if [ -f app-unpriv/build/outputs/native-debug-symbols/release/native-debug-symbols.zip ]; then
            cp app-unpriv/build/outputs/native-debug-symbols/release/native-debug-symbols.zip app-unpriv/build/outputs/apk/release/
          fi

      - name: Set Dynamic Tag Name
        id: tag
        run: |
          if [ -n "${{ github.ref_name }}" ] && [ "${{ github.ref_type }}" = "tag" ]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          name: Release ${{ steps.tag.outputs.TAG_NAME }}
          files: |
            app-unpriv/build/outputs/apk/release/*.apk
            app-unpriv/build/outputs/apk/release/*.zip
          body: |
            Automated Release for ${{ steps.tag.outputs.TAG_NAME }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
